### ISSUE TITLE
downloadable release of jar file

### ISSUE THREAD

**Issue by christiangierschner** [datasharingframework/dsf-process-allow-list#6]
Hi @hhund 
i'm updating my dsf ansible setup automation and i cant download the dsf-process-allow-list-1.0.0.0-M1.jar..

Could you please supply a release, so i can curl the file from my bpe server?

Thanks
Christian

**Comment by hhund** [comment]
See https://github.com/datasharingframework/dsf-process-allow-list/releases/tag/v1.0.0.0
